export type ExamQuestion = {
  id: string;
  q: string;
  options: string[];
  answer: number;
  explain: string;
};

export type ExamBank = {
  pathSlug: string;
  title: string;
  timeMinutes: number;
  passingPercent: number;
  questions: ExamQuestion[];
};

export const EXAM_BANKS: Record<string, ExamBank> = {
  "soc-analyst": {
    pathSlug: "soc-analyst",
    title: "SomTrust SOC Analyst Certification Exam",
    timeMinutes: 60,
    passingPercent: 70,
    questions: [
      {
        id: "e1",
        q: "Metrics-ka SOC waa in loo isticmaalo?",
        options: ["Si loo hagaajiyo nidaamka guud", "Si loo canaanto analyst gaar ah", "Si loo eryo shaqaalaha", "Ma jiraan faa'iido"],
        answer: 0,
        explain: "Metrics wanaagsan waxay taageeraan hagaajinta nidaamka, ma aha canaanashada shaqsiyaadka.",
      },
      {
        id: "e2",
        q: "Talo wanaagsan waxay leedahay?",
        options: ["Owner iyo waqti go'an", "Erayo badan", "Diagram keliya", "Magac shakhsi la eedeeyay"],
        answer: 0,
        explain: "Actionable = cid mas'uul ah + waqti.",
      },
      {
        id: "e3",
        q: "ss -tunap waxay muujisaa?",
        options: ["Xiriirrada network-ka furan", "Files kaydsan", "Users-ka system-ka", "CPU temperature"],
        answer: 0,
        explain: "ss wuxuu bixiyaa macluumaad ku saabsan network connections.",
      },
      {
        id: "e4",
        q: "SIEM shaqadiisu waa?",
        options: ["Ururinta iyo falanqaynta logs si loo helo alerts", "Otomaatig gareynta tallaabooyinka", "La socodka endpoint-yada oo keliya", "Kaydinta backup"],
        answer: 0,
        explain: "SIEM waa xarunta ururinta iyo correlation-ka logs.",
      },
      {
        id: "e5",
        q: "NTLM marka la barbardhigo Kerberos waa?",
        options: ["Mid ka hooseeya security ahaan", "Mid ka horumarsan Kerberos", "Isku mid", "Ma la isticmaalo Windows"],
        answer: 0,
        explain: "NTLM waa protocol hore oo aan lahayn encryption xoog u dhiganta Kerberos.",
      },
      {
        id: "e6",
        q: "Sigma rule wuxuu ku daraa?",
        options: ["Falsepositives iyo level (severity)", "Kaliya title", "Kaliya IP", "Kaliya password"],
        answer: 0,
        explain: "Sigma rule dhamaystiran wuxuu bixiyaa faahfaahin dheeraad ah.",
      },
      {
        id: "e7",
        q: "False positive waa?",
        options: ["Alert aan threat dhab ah ahayn", "Weerar guuleystay", "Backup", "Password"],
        answer: 0,
        explain: "False positive wuxuu keenaa alert laakiin khatar ma jirto.",
      },
      {
        id: "e8",
        q: "Alert fatigue wuxuu keeni karaa?",
        options: ["In true positives dhab ah la seego", "In CPU la kordhiyo", "In backup la sameeyo", "In network la joojiyo"],
        answer: 0,
        explain: "Alerts badan oo aan macno lahayn ayaa daaliya analyst-ka.",
      },
      {
        id: "e9",
        q: "Sababta exclusions loo daro rule-kan waa?",
        options: ["Si loo yareeyo false positives service accounts caadiga ah", "Si loo kordhiyo alerts", "Si loo tirtiro rule-ka", "Ma jiro sabab"],
        answer: 0,
        explain: "Service accounts qaarkood si caadi ah ayay u weydiiyaan service tickets badan.",
      },
      {
        id: "e10",
        q: "Header-kee ayaa muujinaya natiijada SPF/DKIM?",
        options: ["Subject", "Authentication-Results", "MIME-Version", "Content-Type"],
        answer: 1,
        explain: "Authentication-Results wuxuu muujiyaa spf=, dkim=, dmarc=.",
      },
      {
        id: "e11",
        q: "Sababta network segmentation loo isticmaalo waa?",
        options: ["Si haddii hal qayb la jebiyo, attacker-ku aanu si fudud u gudbin meel kale", "Si loo kordhiyo internet speed", "Si loo beddelo hardware", "Si loo sameeyo backup"],
        answer: 0,
        explain: "Segmentation waxay xannibaysaa lateral movement.",
      },
      {
        id: "e12",
        q: "Prefetch files waxay muujiyaan?",
        options: ["Programs la fuliyay iyo waqtiyada la fuliyay", "Kaliya browser history", "Kaliya email", "Kaliya passwords"],
        answer: 0,
        explain: "Prefetch waa artifact muhiim ah oo execution evidence ah.",
      },
      {
        id: "e13",
        q: "Pyramid of Pain, heerkee ayaa ugu adag attacker-ku inuu beddelo?",
        options: ["TTPs", "Hash values", "IP addresses", "Domain names"],
        answer: 0,
        explain: "TTPs waa habka attacker-ku ku shaqeeyo — beddelkiisu waa mid qaali ah.",
      },
      {
        id: "e14",
        q: "Double extortion macnaheedu waa?",
        options: ["Xog la xaday oo lagu hanjabo daabacaad, marka lagu daro encryption", "Labo malware oo isku mar shaqeeya", "Lacag laba jeer la bixiyo", "Backup laba jeer la sameeyo"],
        answer: 0,
        explain: "Ransomware casriga ah wuxuu isticmaalaa labo cadaadis: encryption + xog daabacaad.",
      },
      {
        id: "e15",
        q: "Urgency iyo scarcity waxay ku saameeyaan?",
        options: ["Fikirka fiican ee qofka, iyagoo cadaadin ku sameeya inuu si degdeg ah u falceliyo", "CPU-ga computer-ka", "Firewall rules", "Network bandwidth"],
        answer: 0,
        explain: "Cadaadiska waqtiga wuxuu joojiyaa fikirka taxadarka leh.",
      },
      {
        id: "e16",
        q: "Sababta la hubiyo source-ka OSINT waa?",
        options: ["Ma dhammaan OSINT waa la aamini karaa — accuracy way kala duwan tahay", "OSINT waligeed waa sax", "Ma jiro sabab in la hubiyo", "OSINT waa mid keliya"],
        answer: 0,
        explain: "Verification-ku waa muhiim si loo yareeyo qaladaad.",
      },
      {
        id: "e17",
        q: "sudo -l waxay muujisaa?",
        options: ["Waxa user-ku sudo u fulin karo", "Files kaydsan", "Network connections", "CPU usage"],
        answer: 0,
        explain: "sudo -l wuxuu liistaa amarrada user-ku u oggolaaday.",
      },
      {
        id: "e18",
        q: "Rule cusub oo 500 alert maalintii dhaliya waa in?",
        options: ["La tuun-gareeyo (tuning) ama la joojiyo — alert fatigue waa khatar", "La daayo sidiisa", "Severity-giisa la kordhiyo", "Analyst kale loo diro"],
        answer: 0,
        explain: "Alert fatigue wuxuu keenaa in weerarrada dhabta ah la seego.",
      },
      {
        id: "e19",
        q: "ISC2 CC waa?",
        options: ["Certification bilaash ah oo aasaasi ah", "Certification qaali ah oo heer sare ah", "Nooc SIEM ah", "Malware nooc ah"],
        answer: 0,
        explain: "ISC2 CC waa entry-level oo bilaash ah.",
      },
      {
        id: "e20",
        q: "Linux waxaa badanaa loo isticmaalaa?",
        options: ["Servers iyo cybersecurity tools", "Kaliya games", "Kaliya phones", "Kaliya printers"],
        answer: 0,
        explain: "Linux waa muhiim servers iyo security environments.",
      },
      {
        id: "e21",
        q: "Warbixinta ugu dambaysa waa in ay ku jirto?",
        options: ["Root cause analysis iyo recommendations owner/waqti leh", "Kaliya magaca employee-ga khaldamay", "Kaliya lacagta lumay", "Ma jiro waxa lagu daraa"],
        answer: 0,
        explain: "Warbixin dhamaystiran waxay u baahan tahay root cause iyo actionable recommendations.",
      },
      {
        id: "e22",
        q: "KQL waxaa loo isticmaalaa?",
        options: ["Microsoft Sentinel/Defender", "Splunk oo keliya", "Wazuh oo keliya", "Linux command line"],
        answer: 0,
        explain: "KQL waa luqadda Microsoft security tools-kiisa.",
      },
      {
        id: "e23",
        q: "Sababta Linux muhiim ugu yahay SOC analyst waa?",
        options: ["Server-yada badan, security tools iyo cloud waxay ku shaqeeyaan Linux", "Linux waa mid fudud oo keliya loo isticmaalo games", "Linux ma taageero networking", "Windows oo keliya ayaa loo isticmaalaa security"],
        answer: 0,
        explain: "Linux waa aasaas u ah infrastructure-ka casriga ah ee servers iyo security tools.",
      },
      {
        id: "e24",
        q: "Haddii chain of custody-ga uu jabo, natiijadu waa?",
        options: ["Caddayntu maxkamad kuma shaqayn karto", "Wax dhib ah ma jiraan", "Evidence-ku wuu hagaagaa", "Backup si otomaatig ah ayaa loo sameeyaa"],
        answer: 0,
        explain: "Chain of custody-ga oo jaban wuxuu keenaa in caddaynta la shaki galo.",
      },
      {
        id: "e25",
        q: "SUID bit-ku muxuu sameeyaa?",
        options: ["Program-ka wuxuu u shaqeeyaa sida owner-kiisa (badanaa root)", "Wuxuu kordhiyaa CPU speed", "Wuxuu tirtiraa file-ka", "Wuxuu xiraa internet-ka"],
        answer: 0,
        explain: "SUID wuxuu bixiyaa awood gaar ah — weeraryahannada ayaa raadiya inay ka faa'iidaystaan.",
      },
      {
        id: "e26",
        q: "sudo commands-ka waxaa lagu diiwaan geliyaa?",
        options: ["/var/log/auth.log", "/tmp", "/home", "/etc/hosts"],
        answer: 0,
        explain: "auth.log wuxuu diiwaan geliyaa authentication iyo sudo activity.",
      },
      {
        id: "e27",
        q: "Digital footprint reduction waxay caawisaa?",
        options: ["Yareynta macluumaadka attacker-ku isticmaali karo", "Kordhinta CPU", "Kordhinta internet speed", "Ma jiro faa'iido"],
        answer: 0,
        explain: "In yar oo la soo bandhigo ayaa ka dhigaya pretexting mid ka adag.",
      },
      {
        id: "e28",
        q: "Tactic-kee ayaa ku saabsan sidii weeraryahanku u sii joogi lahaa nidaamka?",
        options: ["Persistence", "Discovery", "Collection", "Impact"],
        answer: 0,
        explain: "Persistence = sii joogitaanka dib-u-shidista kadib.",
      },
      {
        id: "e29",
        q: "Sababta attackers PowerShell jecel yihiin waa?",
        options: ["Waxay awood u leedahay memory-ga si toos ah, kumana baahna install", "Waa mid aad u gaabis oo aan awood badnayn", "Kaliya waxaa loo isticmaali karaa websites", "Ma shaqeyso Windows kasta"],
        answer: 0,
        explain: "PowerShell wuxuu u oggolaadaa fileless attacks iyo living-off-the-land techniques.",
      },
      {
        id: "e30",
        q: "Diamond Model wuxuu isku xiraa?",
        options: ["Adversary, Capability, Infrastructure, Victim", "Firewall, Antivirus, VPN, Backup", "SIEM, SOAR, EDR, IDS", "TCP, UDP, IP, DNS"],
        answer: 0,
        explain: "Diamond Model waa framework caan ah oo threat intelligence-ka lagu isticmaalo.",
      },
      {
        id: "e31",
        q: "Registry Run Keys waxay caawiyaan?",
        options: ["Programs inay si otomaatig ah ugu shaqeeyaan login kasta", "Kordhinta CPU speed", "Kaydinta files", "Xiritaanka internet-ka"],
        answer: 0,
        explain: "Run keys waa meel caan ah oo malware ku isticmaalo si uu ugu sii jiro.",
      },
      {
        id: "e32",
        q: "Authentication maxay qabataa?",
        options: ["Waxay xaqiijisaa aqoonsiga", "Waxay sameysaa backup", "Waxay kordhisaa RAM", "Waxay beddeshaa IP"],
        answer: 0,
        explain: "Authentication waxay xaqiijisaa qofka ama device-ka.",
      },
      {
        id: "e33",
        q: "TLP level-ka waxaa loo daraa report-ka si?",
        options: ["Loo qeexo heerka qarsoodiga macluumaadka", "Loo kordhiyo bogagga", "Loo tirtiro logs", "Ma jiro sabab"],
        answer: 0,
        explain: "TLP wuxuu hagaa cidda macluumaadka la wadaagi karo.",
      },
      {
        id: "e34",
        q: "Permission khaldan wuxuu keeni karaa?",
        options: ["Privilege escalation", "CPU cusub", "Internet degdeg ah", "Battery cusub"],
        answer: 0,
        explain: "Attackers waxay isticmaali karaan permissions khaldan.",
      },
      {
        id: "e35",
        q: "HTTPS traffic maxaa dhib ka dhigi kara analysis?",
        options: ["Encryption", "CPU speed", "Screen size", "Storage"],
        answer: 0,
        explain: "Encryption waxay qarin kartaa content-ka traffic.",
      },
      {
        id: "e36",
        q: "C2 server sababta uu muhiim u yahay waa?",
        options: ["Wuxuu bixiyaa amarro malware-ka una diraa xog attacker-ka", "Wuxuu ilaaliyaa antivirus-ka", "Wuxuu sameeyaa backup", "Wuxuu kordhiyaa RAM"],
        answer: 0,
        explain: "C2 waa xariiqda isgaarsiinta ee malware-ka iyo attacker-ka.",
      },
      {
        id: "e37",
        q: "Login logs Debian/Ubuntu waxaa laga helaa?",
        options: ["/var/log/auth.log", "/home", "/tmp", "/etc/hosts"],
        answer: 0,
        explain: "auth.log waa meesha login iyo sudo activity.",
      },
      {
        id: "e38",
        q: "Difaaca ugu wanaagsan ee BEC waa?",
        options: ["Xaqiijin channel kale ah (wicitaan lambar la yaqaan)", "Si dhakhso ah u sameyso amarka madaxa", "U dir email-ka IT-ga oo sug", "Ku dar madaxa CC"],
        answer: 0,
        explain: "Out-of-band verification ayaa joojisa BEC intooda badan.",
      },
      {
        id: "e39",
        q: "Cron job cusub oo 5 daqiiqo kasta ku shaqeeya script /tmp ku jira waa?",
        options: ["Backup caadi ah", "Persistence shaki leh — baar oo go'doomi", "Update nidaamka", "Log rotation"],
        answer: 1,
        explain: "/tmp + cron = qaab persistence caan ah.",
      },
      {
        id: "e40",
        q: "Virtual machine waa maxay?",
        options: ["Computer software ahaan u shaqeeya", "Password", "Firewall", "Network cable"],
        answer: 0,
        explain: "VM waa system virtual ah oo ku shaqeeya physical hardware.",
      },
      {
        id: "e41",
        q: "Tool natiijo keeno analyst-ku waa inuu?",
        options: ["Fahmo oo xaqiijiyo natiijada", "Si toos ah u aamino", "Tirtiraa system-ka", "Iska indho tiro"],
        answer: 0,
        explain: "Tools waxay bixiyaan xog, analyst-kuna wuxuu sameeyaa go'aan.",
      },
      {
        id: "e42",
        q: "Sababta la isku daro threat report TTPs iyo ATT&CK techniques waa?",
        options: ["Si loo barbardhigo groups kala duwan lana go'aamiyo detection coverage", "Si loo kordhiyo RAM", "Si loo tirtiro logs", "Ma jiro sabab"],
        answer: 0,
        explain: "Mapping-ku wuxuu kaa caawiyaa fahamka gaps-ka detection-kaaga.",
      },
      {
        id: "e43",
        q: "End-to-end simulation-ku wuxuu isku darayaa?",
        options: ["Dhammaan xirfadaha module-yada hore (networking, endpoint, threat, SIEM, IR)", "Kaliya networking", "Kaliya forensics", "Kaliya reporting"],
        answer: 0,
        explain: "Capstone-ku wuxuu isku daraa dhammaan waxa aad baratay.",
      },
      {
        id: "e44",
        q: "Internet-ka wuxuu inta badan isticmaalaa model kee?",
        options: ["TCP/IP", "HTML", "CPU", "BIOS"],
        answer: 0,
        explain: "TCP/IP waa aasaaska communication-ka internet-ka.",
      },
      {
        id: "e45",
        q: "Tallaabada ugu horreysa ee SIEM pipeline waa?",
        options: ["Collection", "Alerting", "Reporting", "Containment"],
        answer: 0,
        explain: "Marka hore log-yada ayaa la ururiyaa.",
      },
      {
        id: "e46",
        q: "Apache oo dhalay bash shell waa?",
        options: ["Calaamad caadi ah", "Suspicious parent-child chain — u baahan baaritaan", "Cilad hardware ah", "Update software"],
        answer: 1,
        explain: "Web server oo furaya shell waa indicator caan ah oo compromise ah.",
      },
      {
        id: "e47",
        q: "Preparation phase-ka wuxuu ka kooban yahay?",
        options: ["Playbooks, tools, backups, tababar", "Kaliya baaritaanka incident dhab ah", "Kaliya containment", "Kaliya reporting"],
        answer: 0,
        explain: "Preparation waa u diyaarinta ka hor incident-ku inuu dhaco.",
      },
      {
        id: "e48",
        q: "Threat intelligence ujeeddadeeda ugu weyn waa?",
        options: ["In la fahmo cadowga si defense-ka loo hagaajiyo", "In la sameeyo malware", "In la kordhiyo RAM", "In la beddelo hardware"],
        answer: 0,
        explain: "Intelligence-ka waxaa loo isticmaalaa in la fahmo oo laga hortago threats.",
      },
      {
        id: "e49",
        q: "SOC analyst sababtee u isticmaalaa OSI model?",
        options: ["Si uu u fahmo halka dhibaatada network ka jirto", "Si uu u beddelo hardware", "Si uu u sameeyo passwords", "Si uu u rakibo games"],
        answer: 0,
        explain: "OSI model wuxuu caawiyaa troubleshooting iyo investigation.",
      },
      {
        id: "e50",
        q: "P1 severity macnaheedu waa?",
        options: ["Halka ugu daran/mudnaanta ugu sarreysa", "Halka ugu hooseysa", "Backup guulaystay", "Update software"],
        answer: 0,
        explain: "P1 waa severity-ga ugu sarreeya oo u baahan falcelinta ugu degdegga badan.",
      },
    ],
  },
  "ethical-hacking": {
    pathSlug: "ethical-hacking",
    title: "SomTrust Ethical Hacking Certification Exam",
    timeMinutes: 60,
    passingPercent: 70,
    questions: [
      {
        id: "e1",
        q: "A09 sababta muhiim u yahay SOC labadaba waa?",
        options: ["Haddii aan la diiwaan gelin, attacks waxay dhici karaan iyada oo aan la ogaan", "Ma jiro saameyn", "Kaliya pentest ayaa khusaysa", "Kaliya developers ayaa khusaysa"],
        answer: 0,
        explain: "Logging failures waxay saameeyaan detection capability-ga oo dhan.",
      },
      {
        id: "e2",
        q: "Output encoding waxay ka hortagtaa?",
        options: ["Browser-ka inuu u fasiro user input sida code ah", "Database-ka inuu shaqeeyo", "Network-ka inuu xiriiro", "Ma jiro faa'iido"],
        answer: 0,
        explain: "Encoding wuxuu beddelaa characters khaldan HTML entities ah.",
      },
      {
        id: "e3",
        q: "Meterpreter faa'iidadeeda ugu weyn waa?",
        options: ["Wuxuu ka shaqeeyaa memory-ga (in-memory), aan disk-ka la taaban", "Wuxuu u baahan yahay disk access buuxa", "Wuxuu kaliya scan gareeyaa", "Ma jiro faa'iido gaar ah"],
        answer: 0,
        explain: "In-memory execution-ku wuxuu yareeyaa evidence disk-ka ku hara.",
      },
      {
        id: "e4",
        q: "OSINT public data ahaan waa in la isticmaalo?",
        options: ["Kaliya scope-ka authorized gudihiisa", "Si xor ah, ma jiro xaddid", "Ma jiro sabab ethical ah", "Kaliya law enforcement"],
        answer: 0,
        explain: "Public availability kuma filna in xad-gudub la sameeyo privacy-ga.",
      },
      {
        id: "e5",
        q: "-sV wuxuu isku dayaa inuu aqoonsado?",
        options: ["Version-ka software-ka ku shaqeynaya port kasta", "Password-ka user-ka", "IP address-ka router-ka", "MAC address-ka"],
        answer: 0,
        explain: "Version detection wuxuu caawiyaa la aqoonsado vulnerabilities-ka la xiriira.",
      },
      {
        id: "e6",
        q: "Tallaabada ugu horreysa ee scanning methodology waa?",
        options: ["Host discovery — ogaanshaha hosts-ka nool", "NSE vulnerability scripts", "OS fingerprinting", "Banner grabbing"],
        answer: 0,
        explain: "Marka hore waa in la ogaado hosts-ka jira ka hor la scan-gareeyo ports.",
      },
      {
        id: "e7",
        q: "sudo -l waxay muujisaa?",
        options: ["Waxa user-ku sudo u fulin karo", "Password-ka root", "Network connections", "Disk space"],
        answer: 0,
        explain: "Misconfigurations sudo-ga waxaa lagu ogaan karaa amarkan.",
      },
      {
        id: "e8",
        q: "Executive summary-gu waa in uu ku jiro?",
        options: ["Heerka guud ee risk-ka iyo goals la gaadhay", "Kaliya command-yada isticmaalay", "Kaliya raw scan output", "Ma jiro shuruud"],
        answer: 0,
        explain: "Maamulku wuxuu rabaa summary, ma aha faahfaahin technical.",
      },
      {
        id: "e9",
        q: "Burp Proxy-ga default port-kiisu waa?",
        options: ["8080", "80", "443", "22"],
        answer: 0,
        explain: "127.0.0.1:8080 waa default proxy listener-ka Burp.",
      },
      {
        id: "e10",
        q: "Decoy scanning (-D) wuxuu sameeyaa?",
        options: ["Ku daraa IP addresses been ah si la is-jugleeyo", "Wuxuu tirtiraa IP-ga dhabta ah", "Wuxuu xakameeyaa firewall-ka", "Wuxuu beddelaa DNS"],
        answer: 0,
        explain: "Decoys waxay ka adkeeyaan defender-ka inuu ogaado scanner-ka dhabta ah.",
      },
      {
        id: "e11",
        q: "Subdomain enumeration muhiimaddeedu waa?",
        options: ["Waxay muujisaa attack surface ballaaran (dev, staging, api subdomains)", "Waxay tirtirtaa DNS records", "Waxay xakameysaa firewall", "Waxay beddeshaa IP"],
        answer: 0,
        explain: "Subdomains-ku badanaa waa meelo ka hoosaysa security-gooda ka hooseeya production.",
      },
      {
        id: "e12",
        q: "Information gathering phase-ku wuxuu isku xiraa?",
        options: ["Xirfadaha recon-ka aad hore u baratay", "Kaliya password cracking", "Kaliya social engineering", "Ma jiro xiriir"],
        answer: 0,
        explain: "Recon-ku waa saldhig u ah web app testing methodology-ga.",
      },
      {
        id: "e13",
        q: "Repeater waxaa loo isticmaalaa marka?",
        options: ["Manual, focused testing hal request ah", "Automated bulk testing", "Reporting", "Recon"],
        answer: 0,
        explain: "Repeater-ku ku habboon yahay tijaabin gaar ah oo focused ah.",
      },
      {
        id: "e14",
        q: "CVSS Base Score-ka waxaa ka mid ah?",
        options: ["Attack Vector, Attack Complexity, Privileges Required", "Kaliya magaca vulnerability-ga", "Kaliya waqtiga la helay", "Kaliya vendor-ka"],
        answer: 0,
        explain: "Components-kan waxay isku dhufaan si loo helo score-ka.",
      },
      {
        id: "e15",
        q: "SCA tools waxay ogaadaan?",
        options: ["Vulnerable dependencies/libraries la isticmaalo", "Passwords la xaday", "Network traffic shaki leh", "Email phishing"],
        answer: 0,
        explain: "SCA waxay falanqeeyaan dependencies-ka software-ka.",
      },
      {
        id: "e16",
        q: "Full pentest simulation-ku wuxuu isku daraa?",
        options: ["Dhammaan xirfadaha 8-da module ee koorsadan", "Kaliya scanning", "Kaliya reporting", "Kaliya exploitation"],
        answer: 0,
        explain: "Capstone-ku wuxuu isku daraa recon, scanning, web security, exploitation, iyo reporting.",
      },
      {
        id: "e17",
        q: "Living off the Land (LotL) wuxuu ka dhigaa detection?",
        options: ["Mid adag, sababtoo ah tools-ku waa kuwa legit ah", "Mid aad u fudud", "Mid aan suurtagal ahayn", "Ma jiro saameyn"],
        answer: 0,
        explain: "Tools legit ah waxay ka dhigaan attacker behavior mid u eg admin caadi ah.",
      },
      {
        id: "e18",
        q: "Attack surface web app ah wuxuu ka kooban yahay?",
        options: ["Input fields, cookies, APIs, file uploads", "Kaliya server hardware", "Kaliya CPU-ga", "Kaliya network cables"],
        answer: 0,
        explain: "Dhammaan meelaha xogta la geliyo ama la beddeli karo waa attack surface.",
      },
      {
        id: "e19",
        q: "Nikto waxaa loo isticmaalaa?",
        options: ["Baaritaanka degdegga ah ee web server misconfigurations", "Password cracking", "Network scanning", "Ma jiro isticmaal"],
        answer: 0,
        explain: "Nikto-gu wuxuu diiradda saaraa web server-ka configuration-kiisa.",
      },
      {
        id: "e20",
        q: "'Assumption of breach' thinking-ku wuxuu bixiyaa?",
        options: ["Aragtida attacker-ka, ma aha kaliya defender-ka", "Kaliya defender-ka aragtidiisa", "Ma jiro faa'iido", "Kaliya loo isticmaalo forensics"],
        answer: 0,
        explain: "Fikirkani wuxuu kordhinayaa waxa aad ka heli karto system-ka.",
      },
      {
        id: "e21",
        q: "; cat /etc/passwd ku darista input field wuxuu tusinayaa?",
        options: ["Command Injection", "XSS", "CSRF", "SSRF"],
        answer: 0,
        explain: "Ku darista commands additional ah system-ka waa command injection.",
      },
      {
        id: "e22",
        q: "Email format discovery waxay u ogolaataa attacker?",
        options: ["Sameynta guesses email addresses shaqaalaha kale", "Xadhig ka jebinta password-ka", "Xiritaanka accounts", "Beddelidda MFA"],
        answer: 0,
        explain: "Haddii hal formula la ogaado, waxaa laga soo qaadan karaa email addresses kale.",
      },
      {
        id: "e23",
        q: "Tallaabada ugu dambaysa ee assessment process-ka waa?",
        options: ["Remediation tracking", "Planning", "Discovery", "Scanning"],
        answer: 0,
        explain: "Assessment-ku ma dhammaan haddii aan la la socon in vulnerabilities la xaliyay.",
      },
      {
        id: "e24",
        q: "Time-based blind SQLi wuxuu isticmaalaa?",
        options: ["SLEEP() si loo ogaado condition-ka iyada oo lagu eegayo waqtiga response-ka", "Error messages toos ah", "UNION SELECT", "Kaliya GET requests"],
        answer: 0,
        explain: "Marka waqtiga response-ku sii dheeraado, taasi waxay muujisaa condition-ku inuu run yahay.",
      },
      {
        id: "e25",
        q: "Rate limiting active scanning ahaan muhiim u yahay?",
        options: ["Si aan production-ka loo saameyn", "Ma jiro sabab", "Kordhinta accuracy oo keliya", "Kaliya loo isticmaalo billing"],
        answer: 0,
        explain: "Traffic aad u badan wuxuu khatar gelin karaa performance-ka production-ka.",
      },
      {
        id: "e26",
        q: "Session fixation waa?",
        options: ["Attacker qeexaya session ID victim-ka ka hor login", "Xadidda dhammaan sessions", "Beddelidda password-ka", "Kordhinta session timeout"],
        answer: 0,
        explain: "Attacker-ku wuxuu ku qasbaa victim-ka inuu isticmaalo session ID uu horay u yaqaan.",
      },
      {
        id: "e27",
        q: "Purple team-ku wuxuu sameeyaa?",
        options: ["Isku daraya red iyo blue team si labaduba loo hormariyo", "Kaliya offensive testing", "Kaliya defensive monitoring", "Ma jiro sababaha loo isticmaalo"],
        answer: 0,
        explain: "Purple team-ku wuxuu xoojiyaa isgaarsiinta u dhaxaysa red iyo blue teams.",
      },
      {
        id: "e28",
        q: "'; cat /etc/passwd' payload-ku waa tusaale?",
        options: ["Command Injection", "SQL Injection", "XSS", "CSRF"],
        answer: 0,
        explain: "Ku darista commands additional ah system-ka waa command injection.",
      },
      {
        id: "e29",
        q: "Miisaaniyad xaddidan sababta loo dooran lahaa OpenVAS waa?",
        options: ["Waa bilaash, ma aha commercial sida Nessus Pro", "Waa mid ka fiican dhammaan", "Ma jiro sabab", "OpenVAS ma shaqeeyo"],
        answer: 0,
        explain: "Budget constraints waxay khusaysaa doorashada tools.",
      },
      {
        id: "e30",
        q: "FTP anonymous access tijaabintiisu waa muhiim sababtoo ah?",
        options: ["Waxay siin kartaa access files ka horreysay authentication buuxa", "Ma jiro faa'iido", "Kaliya loo isticmaalo backup", "Waa waajib FTP kasta"],
        answer: 0,
        explain: "Misconfiguration-kani waa hab caan ah oo initial access ah.",
      },
      {
        id: "e31",
        q: "Xalka ugu wanaagsan waa?",
        options: ["Ka fogow deserializing untrusted data, isticmaal JSON + signing", "Kaliya encrypt gareynta data", "Ma jiro xal", "Kaliya kordhinta logging"],
        answer: 0,
        explain: "JSON fudud (aan lahayn magic methods) waa mid ka ammaan badan.",
      },
      {
        id: "e32",
        q: "HTTP History waxay kaydisaa?",
        options: ["Dhammaan requests/responses session-ka", "Kaliya requests khaldan", "Kaliya passwords", "Kaliya cookies"],
        answer: 0,
        explain: "Waxay bixisaa log dhamaystiran oo browsing session-ka aad ku sameysay.",
      },
      {
        id: "e33",
        q: "SSRF tusaale caan ah waa?",
        options: ["Isticmaalka image URL field si loo gaaro cloud metadata endpoint", "Ku gelinta script HTML page ah", "Isku dayo password badan", "Diirinta email khiyaano ah"],
        answer: 0,
        explain: "Cloud metadata endpoints waa targets caan ah oo SSRF ah.",
      },
      {
        id: "e34",
        q: "WHOIS wuxuu bixiyaa?",
        options: ["Macluumaad domain registration ah", "Password-ka website-ka", "Source code-ka website-ka", "Server IP oo keliya"],
        answer: 0,
        explain: "WHOIS wuxuu daboolaa registrant, registrar iyo taariikhaha.",
      },
      {
        id: "e35",
        q: "Automated testing wuxuu jabin karaa sababtoo ah?",
        options: ["CSRF/session tokens isbeddela request kasta", "Ma jiro sabab", "Automated tools waligood way jabaan", "Kaliya loo isticmaalo manual testing"],
        answer: 0,
        explain: "Tokens dynamic ah waxay u baahan yihiin maamul gaar ah.",
      },
      {
        id: "e36",
        q: "BOLA (API1) waa nooca?",
        options: ["IDOR-ka APIs — beddelidda object ID aan authorization la hubin", "SQL injection API ah", "XSS API ah", "Ma jiro macno"],
        answer: 0,
        explain: "BOLA waa vulnerability-ka ugu badan APIs Top 10 gudaheeda.",
      },
      {
        id: "e37",
        q: "Farqiga vulnerability analysis iyo exploitation waa?",
        options: ["Analysis wuxuu helaa/xaqiijiyaa, exploitation wuxuu si dhab ah u isticmaalaa", "Isku mid", "Exploitation wuxuu kaliya helaa", "Ma jiro farqi"],
        answer: 0,
        explain: "Exploitation-ku waa tallaabo action-based ah oo ka sii dambeysa analysis-ka.",
      },
      {
        id: "e38",
        q: "Recon report-ku waa in uu ku jiro?",
        options: ["Subdomains, employees/emails, tech stack, attack surface summary", "Kaliya IP address hal ah", "Kaliya magaca shirkadda", "Ma jiro shuruud"],
        answer: 0,
        explain: "Warbixin dhamaystiran waxay taageertaa marxaladaha xiga ee pentest-ka.",
      },
      {
        id: "e39",
        q: "False negative waa maxay?",
        options: ["Vulnerability dhab ah oo scanner-ku uu seego", "Finding aan dhab ahayn", "Scanner oo aan shaqeynayn", "Report aan la qorin"],
        answer: 0,
        explain: "False negative-ku waa khatar ka sii daran false positive, sababtoo ah threat dhab ah baa la seegayaa.",
      },
      {
        id: "e40",
        q: "Password spraying ka duwan tahay brute force sababtoo ah?",
        options: ["Hal password, accounts badan — ka fogaanaya lockout policies", "Accounts badan, password hal ah — isku mid", "Ma jiro farqi", "Spraying waa mid ka gaabis"],
        answer: 0,
        explain: "Brute force-ku wuxuu diiradda saaraa hal account, spraying-na accounts badan.",
      },
      {
        id: "e41",
        q: "Scope creep waa maxay?",
        options: ["Marka tester-ku uu dhaafo systems la oggol yahay", "Kordhinta miisaaniyadda", "Kordhinta waqtiga pentest-ka", "Ma jiro macno"],
        answer: 0,
        explain: "Scope creep waa khatar sharci ah oo la iska ilaaliyo.",
      },
      {
        id: "e42",
        q: "Prioritization-ku wuxuu ku salaysan yahay?",
        options: ["Exploitability iyo impact", "Kaliya magaca vulnerability-ga", "Kaliya waqtiga la helay", "Ma jiro salax"],
        answer: 0,
        explain: "Severity-gu wuxuu isku daraa sida fudud u ah in la isticmaalo iyo saameynta.",
      },
      {
        id: "e43",
        q: "Pitchfork attack type-ku wuxuu ku habboon yahay?",
        options: ["Testing multiple accounts isla mar (username+password lists labadaba)", "Testing hal password oo keliya", "Sameynta backup", "Scanning ports"],
        answer: 0,
        explain: "Pitchfork wuxuu isticmaalaa wordlists kala duwan isku mid ah positions kala duwan.",
      },
      {
        id: "e44",
        q: "DVWA waxaa loo isticmaalaa?",
        options: ["Tijaabinta web vulnerabilities si ammaan ah", "Backup files", "Encrypt gareynta disk", "Network monitoring"],
        answer: 0,
        explain: "DVWA waa app ula talaal u leh vulnerabilities barasho ahaan.",
      },
      {
        id: "e45",
        q: "Final report-ku waa in uu ku jiro?",
        options: ["Executive summary, findings, remediation roadmap", "Kaliya raw scan output", "Kaliya magacyada categories", "Ma jiro shuruud"],
        answer: 0,
        explain: "Warbixin professional ah waxay u baahan tahay qaybo dhamaystiran.",
      },
      {
        id: "e46",
        q: "Nessus Essentials waa?",
        options: ["Version bilaash ah oo xaddidan", "Version commercial ah oo keliya", "Kaliya open-source", "Ma jiro version bilaash ah"],
        answer: 0,
        explain: "Nessus wuxuu bixiyaa version bilaash ah oo IPs xaddidan leh.",
      },
      {
        id: "e47",
        q: "Sababta lab preparation muhiim u tahay ka hor engagement dhabta ah waa?",
        options: ["Si loo tijaabiyo techniques ammaan ahaan", "Si loo yareeyo miisaaniyadda", "Si loo kordhiyo waqtiga", "Ma jiro sabab"],
        answer: 0,
        explain: "Tijaabinta lab-ka waxay yareysaa khaladaad marka la gaadho system dhabta ah.",
      },
      {
        id: "e48",
        q: "Pass-the-Hash technique-ku wuxuu isticmaalaa?",
        options: ["NTLM hash halkii password cad loo baahnaa", "SSH keys oo keliya", "Kerberos tickets oo keliya", "Certificate files"],
        answer: 0,
        explain: "PtH waa technique caan ah oo lateral movement Windows ah.",
      },
      {
        id: "e49",
        q: "theHarvester -d example.com -b google,linkedin wuxuu sameeyaa?",
        options: ["Ururiya emails/subdomains domain-kan iyada oo la isticmaalayo google iyo linkedin sources", "Wuxuu tirtiraa domain-ka", "Wuxuu sameeyaa backup", "Wuxuu beddelaa DNS records"],
        answer: 0,
        explain: "-d wuxuu qeexayaa domain-ka, -b wuxuu qeexayaa sources-ka.",
      },
      {
        id: "e50",
        q: "UDP scan way ka gaabis badan tahay TCP sababtoo ah?",
        options: ["UDP lacks response caadi ah, ICMP unreachable ayaa loo isticmaalaa", "UDP ma taageero scanning", "UDP waa mid la joojiyay", "Ma jiro sabab"],
        answer: 0,
        explain: "La'aanta response degdeg ah wuxuu ku qasbaa Nmap inuu sugo timeout.",
      },
    ],
  },
  "digital-forensics": {
    pathSlug: "digital-forensics",
    title: "SomTrust Digital Forensics Certification Exam",
    timeMinutes: 60,
    passingPercent: 70,
    questions: [
      {
        id: "e1",
        q: "Secure deletion tools sida sdelete waxay sameeyaan?",
        options: ["Overwrite gareeyaan data marar badan si aan loo soo celin karin", "Waxay backup sameeyaan", "Waxay encrypt gareeyaan oo keliya", "Wax kama beddelaan"],
        answer: 0,
        explain: "Overwriting-ku wuxuu ka dhigaa recovery mid aan macquul ahayn.",
      },
      {
        id: "e2",
        q: "Chain of custody waa?",
        options: ["Diiwaanka isku xigxiga ee cidda haysay evidence-ka waqti kasta", "Kaliya magaca qofka ururiyay evidence-ka", "Kaliya taariikhda la ururiyay", "Ma jiro qeexid gaar ah"],
        answer: 0,
        explain: "Chain of custody-gu waa dhammaan dhaqdhaqaaqa ee evidence-ka.",
      },
      {
        id: "e3",
        q: "Corporate investigations-ku waxay u baahan yihiin?",
        options: ["Authorization gaar ah (employee agreements, company policy)", "Search warrant law enforcement ah oo keliya", "Wax authorization ah looma baahna", "Kaliya IT department approval"],
        answer: 0,
        explain: "Shirkadaha waxay leeyihiin xeerar authorization gaar ah oo ka duwan law enforcement.",
      },
      {
        id: "e4",
        q: "Scenario-based questions waxay tijaabiyaan?",
        options: ["Process-kaaga methodology-ga, ma aha kaliya facts technical ah", "Kaliya typing speed", "Kaliya aqoon academic ah", "Ma jiro ujeeddo"],
        answer: 0,
        explain: "Interviewers-yadu waxay rabaan inay arkaan habka aad u fikirto.",
      },
      {
        id: "e5",
        q: "Systemd service cusub oo dhawaan la abuuray wuxuu tilmaamayaa?",
        options: ["Persistence suurtagal ah — u baahan baaritaan", "Caadi ahaan", "Update software", "Backup process"],
        answer: 0,
        explain: "Services cusub, gaar ahaan kuwo aan la aqoon, waa red flag.",
      },
      {
        id: "e6",
        q: "Multi-source correlation faa'iidadeeda ugu weyn waa?",
        options: ["Dhisidda case dhamaystiran oo aan hal source ku tiirsanayn", "Kordhinta storage", "Ma jiro faa'iido", "Kaliya loo baahan yahay compliance"],
        answer: 0,
        explain: "Log kastaa wuxuu bixiyaa dhinac kala duwan oo dhacdada oo dhan.",
      },
      {
        id: "e7",
        q: "Memory-gu wuxuu bixiyaa context dheeraad ah oo network connections ah sababtoo ah?",
        options: ["Wuxuu isku daraa connection-ka process-ka masuulka ka ah", "Firewall logs waa mid ka fiican marwalba", "Ma jiro faa'iido", "Memory-gu ma bixiyo network data"],
        answer: 0,
        explain: "Firewall logs waxay bixiyaan IP/port, memory-gu wuxuu ku daraa process attribution.",
      },
      {
        id: "e8",
        q: "LNK/Jump Lists waxay caawiyaan xaalado?",
        options: ["USB exfiltration ama data theft investigation", "Kaliya network forensics", "Kaliya malware analysis", "Ma jiro isticmaal forensic ah"],
        answer: 0,
        explain: "Kuwan waxay caddeeyaan file access history user gaar ah.",
      },
      {
        id: "e9",
        q: "Sababta portfolio-gu muhiim u yahay forensics roles waa?",
        options: ["Practical demonstration ayaa loo baahan yahay, gaar ahaan la'aanta experience", "Waa shuruud rasmi ah oo interview", "Ma jiro faa'iido", "Kaliya loo isticmaalo social media"],
        answer: 0,
        explain: "Employers-yadu waxay rabaan inay arkaan hands-on skills.",
      },
      {
        id: "e10",
        q: "Warbixinta ugu dambaysa waa in ay ku jirto?",
        options: ["File system findings, timeline, deleted file recovery results", "Kaliya magaca file-ka la xaday", "Kaliya lambarka case-ka", "Ma jiro shuruud"],
        answer: 0,
        explain: "Report dhamaystiran wuxuu u baahan yahay findings oo dhan si loo taageero go'aanka.",
      },
      {
        id: "e11",
        q: "Autopsy workflow-ku wuxuu bilaabmaa?",
        options: ["Samaynta case cusub", "Isla markiiba warbixinta", "Tirtirida evidence", "Password cracking"],
        answer: 0,
        explain: "Case creation waa tallaabada koowaad ee Autopsy.",
      },
      {
        id: "e12",
        q: "Prefetch files waxay kaydiyaan?",
        options: ["Run count iyo last run timestamp", "Kaliya password", "Kaliya network connections", "Kaliya registry keys"],
        answer: 0,
        explain: "Prefetch wuxuu bixiyaa evidence tira execution ah iyo waqti.",
      },
      {
        id: "e13",
        q: "File carving waxaa loo isticmaalaa marka?",
        options: ["Metadata-du lumeen ama la overwrite gareeyay, laakiin data-gu weli jiro", "Metadata-du weli sax yihiin", "File-ku weligiis ma jirin", "Backup ayaa jira"],
        answer: 0,
        explain: "Carving-ku wuxuu ka shaqeeyaa data raw-ka, ma isticmaalo metadata.",
      },
      {
        id: "e14",
        q: "Superblock wuxuu kaydiyaa?",
        options: ["Metadata guud ee filesystem-ka", "Kaliya files individual", "Kaliya user accounts", "Kaliya passwords"],
        answer: 0,
        explain: "Superblock-ku waa xarunta metadata-ga filesystem-ka oo dhan.",
      },
      {
        id: "e15",
        q: "Data volume weyn oo dhawaan bilaabmay wuxuu tilmaamayaa?",
        options: ["Suurtagal exfiltration ama anomaly u baahan baaritaan", "Caadi", "Backup", "Update software"],
        answer: 0,
        explain: "Anomalies-ka volume-ka waa signal muhiim ah oo NetFlow bixiyo.",
      },
      {
        id: "e16",
        q: "Memory forensics wuxuu caawin karaa encrypted containers sababtoo ah?",
        options: ["RAM-ku wuxuu weli haysan karaa keys haddii container-ku furan yahay", "Memory ma khuseeyo encryption", "Ma jiro faa'iido", "Kaliya loo isticmaalo disk"],
        answer: 0,
        explain: "Keys-ka waxay ku jiraan memory intii container-ku furan yahay.",
      },
      {
        id: "e17",
        q: "Log clearing (1102) la ogaaday, tallaabada xigta waa?",
        options: ["Tijaabinta log recovery unallocated space", "Iska dhaaf, evidence-ku wuu tirmay", "Isla markiiba warbixinta", "Xiritaanka investigation-ka"],
        answer: 0,
        explain: "Fragments waxay weli hari karaan xitaa log clearing kadib.",
      },
      {
        id: "e18",
        q: "Sababta collection order-ku muhiim u yahay scenario-gan waa?",
        options: ["Mashiinku wuu shaqeynayaa — volatile evidence sida memory waa in la ilaaliyaa marka hore", "Ma jiro sabab", "Order-ku kaliya theoretical", "Waqtiga oo keliya ayaa muhiim"],
        answer: 0,
        explain: "Mashiin shaqeynaya wuxuu bixiyaa volatile evidence oo lumi karta.",
      },
      {
        id: "e19",
        q: "Hardware write-blocker wuxuu sameeyaa?",
        options: ["Xannibaya write commands si joogto ah oo qalab jireed ah", "Wuxuu tirtiraa data", "Wuxuu kordhinayaa speed", "Wuxuu encrypt gareeyaa disk"],
        answer: 0,
        explain: "Write-blocker-ku wuxuu ilaaliyaa original-ka wax laga beddelo.",
      },
      {
        id: "e20",
        q: "Cluster waa?",
        options: ["Isku darka sectors dhawr ah oo ah unit-ka ugu yar ee allocation", "File hal ah", "Directory hal ah", "Backup file"],
        answer: 0,
        explain: "File system-ku wuxuu u qaybiyaa disk-ka clusters, ma aha sectors kali ah.",
      },
      {
        id: "e21",
        q: "Sababta timestamp standardization muhiim u tahay waa?",
        options: ["Devices kala duwan waxay isticmaalaan formats kala duwan, isku dar UTC ayaa ka hortagta khaladaad", "Ma jiro sabab", "Timestamps-ku waligood isku mid yihiin", "Kaliya loo baahan yahay Windows"],
        answer: 0,
        explain: "Cross-platform timelines-ku waxay u baahan yihiin standardization si loo iska ilaaliyo qaladaad.",
      },
      {
        id: "e22",
        q: "Event ID 4104 wuxuu la xiriiraa?",
        options: ["PowerShell script block logging", "Login guulaystay", "User cusub la abuuray", "Service la joojiyay"],
        answer: 0,
        explain: "4104 wuxuu diiwaan geliyaa waxa PowerShell scripts-ku ku jiraan.",
      },
      {
        id: "e23",
        q: "Metadata analysis encrypted traffic ahaan wuxuu u ogolaadaa analyst inuu?",
        options: ["Falanqeeyo destination/timing/certificate iyada oo aan content la furin", "Wax kasta uu falanqeeyo sida traffic aan encrypted ahayn", "Wax uu falanqeeyo ma jiraan", "Kaliya passwords uu helo"],
        answer: 0,
        explain: "Metadata-ku wuxuu weli bixiyaa macluumaad qiimo leh.",
      },
      {
        id: "e24",
        q: "Process hollowing waa maxay?",
        options: ["Marka process legit ah la 'hollow' gareeyo oo code khaldan lagu geliyo", "Tirtirida process", "Backup process", "Update software"],
        answer: 0,
        explain: "Process hollowing waa technique defense evasion ah oo caan ah.",
      },
      {
        id: "e25",
        q: "tcp.flags.syn==1 && tcp.flags.ack==0 filter-ku wuxuu muujiyaa?",
        options: ["SYN packets oo keliya (connection attempts cusub)", "Dhammaan traffic", "Kaliya HTTP traffic", "Kaliya DNS queries"],
        answer: 0,
        explain: "Filter-kani wuxuu kala saaraa packets bilowga connection ah.",
      },
      {
        id: "e26",
        q: "Malware oo file-kiisa la tirtiray wuxuu weli ka tagi karaa?",
        options: ["Registry keys, prefetch iyo memory artifacts", "Wax kasta oo dhan waa la tirtiraa si buuxda", "Ma jiro calaamad ka hartay", "Kaliya IP address"],
        answer: 0,
        explain: "Xitaa file la tirtiray, artifacts kale ayaa weli hara.",
      },
      {
        id: "e27",
        q: "sms.db waa?",
        options: ["SQLite database SMS messages kaydiya", "Malware file", "Network configuration", "Backup encryption key"],
        answer: 0,
        explain: "iOS wuxuu isticmaalaa SQLite databases xog badan.",
      },
      {
        id: "e28",
        q: "Forensic analyst-ku wuxuu diiradda saaraa?",
        options: ["Goorma malware la fuliyay, sidee, iyo impact-ka gaarka ah", "Kaliya sida malware-ku guud ahaan u shaqeeyo", "Kaliya code-ka source-ka ah", "Ma jiro diiradda gaar ah"],
        answer: 0,
        explain: "Forensics-ku wuxuu isku xiraa malware-ka dhacdada gaarka ah.",
      },
      {
        id: "e29",
        q: "Qadar badan oo NXDOMAIN responses ah oo isku mid ah waqti gaaban waxay muujin kartaa?",
        options: ["DGA malware oo raadinaya C2 server", "Caadi", "Backup DNS", "Update software"],
        answer: 0,
        explain: "DGA-based malware wuxuu tijaabiyaa domains badan, badankood aan jirin.",
      },
      {
        id: "e30",
        q: "pstree plugin-ku wuxuu muujiyaa?",
        options: ["Processes-ka iyo parent-child relationships", "Kaliya IP addresses", "Kaliya file names", "Kaliya registry keys"],
        answer: 0,
        explain: "pstree wuxuu bixiyaa muuqaal hierarchical ah oo processes ah.",
      },
      {
        id: "e31",
        q: "Memory region leh RWX permissions waa?",
        options: ["Calaamad shaki leh oo la baaro", "Caadi ahaan", "Waa mid la filayo dhammaan processes", "Ma jiro macno"],
        answer: 0,
        explain: "RWX (read/write/execute isla mar) waa aan caadi ahayn oo malware indicator ah.",
      },
      {
        id: "e32",
        q: "USBSTOR registry key wuxuu diiwaan geliyaa?",
        options: ["Dhammaan USB devices hore loo xiray, oo ay ku jiraan serial numbers", "Kaliya USB device hadda ku xiran", "Kaliya passwords", "Kaliya network devices"],
        answer: 0,
        explain: "USBSTOR wuxuu ku hayaa taariikh dheer oo USB devices ah.",
      },
      {
        id: "e33",
        q: "SHA256 waa?",
        options: ["Standard-ka casriga ah ee hashing forensics ah", "Algorithm duugoobay oo aan la isticmaalin", "Encryption algorithm oo keliya", "Compression tool"],
        answer: 0,
        explain: "SHA256 ayaa maanta loo isticmaalaa evidence integrity.",
      },
      {
        id: "e34",
        q: "Attacker-yadu waxay ka fogaan karaan bash_history iyagoo?",
        options: ["Unset HISTFILE ama tirtiro file-ka", "Ma jirto hab loo ilaaliyo", "Waligeed lama tirtiro", "Bash history-ga si otomaatig ah ayaa u backup gareysa"],
        answer: 0,
        explain: "Techniques anti-forensic ah waxay xannibi karaan history logging-ka.",
      },
      {
        id: "e35",
        q: "Autopsy waa?",
        options: ["Tool bilaash ah oo GUI ah oo disk forensics ah", "Tool memory forensics oo keliya", "Tool mobile forensics oo keliya", "Hardware write-blocker"],
        answer: 0,
        explain: "Autopsy waa mid ka mid ah tools-ka ugu caansan disk analysis-ka.",
      },
      {
        id: "e36",
        q: "Memory forensics wuxuu diiradda saaraa?",
        options: ["RAM", "Disk storage", "Network traffic", "Mobile devices"],
        answer: 0,
        explain: "Memory forensics-ku wuxuu falanqeeyaa xogta ku jirta RAM waqtiga la qabtay.",
      },
      {
        id: "e37",
        q: "Sababta mobile forensics uu takhasus u yahay waa?",
        options: ["Encryption default ah, hardware proprietary ah, cloud sync", "Waa mid ka fudud disk forensics", "Ma jiro caqabado gaar ah", "Mobile devices ma leh xog qiimo leh"],
        answer: 0,
        explain: "Caqabadahan waxay u baahan yihiin aqoon iyo tools gaar ah.",
      },
      {
        id: "e38",
        q: "Khilaaf u dhexeeya $STANDARD_INFORMATION iyo $FILE_NAME wuxuu tilmaamayaa?",
        options: ["Timestomping suurtagal ah", "Caadi ahaan", "Backup process", "Update software"],
        answer: 0,
        explain: "Attacker-yadu badanaa waxay kaliya beddelaan $STANDARD_INFORMATION, ma taaban $FILE_NAME.",
      },
      {
        id: "e39",
        q: "File system acquisition waa mid u dhexeeya sababtoo ah?",
        options: ["Wuxuu soo saaraa files/directories oo dhan, aan daboolin unallocated", "Isku mid physical acquisition", "Isku mid logical acquisition", "Ma jiro farqi"],
        answer: 0,
        explain: "Waa balance u dhexeeya faahfaahinta iyo fudaydka.",
      },
      {
        id: "e40",
        q: "Network forensics ka duwan yahay monitoring caadiga ah sababtoo ah?",
        options: ["Waxay diiradda saartaa dib-u-eegista dhacdooyin hore", "Isku mid", "Monitoring-ku ma jirto", "Forensics-ku waa mid real-time ah oo keliya"],
        answer: 0,
        explain: "Forensics-ku waa habka dib-u-eegista, ma aha real-time alerting oo keliya.",
      },
      {
        id: "e41",
        q: "Linux server investigation-ka, artifact-yada ugu qiimaha badan waa?",
        options: ["journald logs, systemd/cron persistence, bash_history", "Kaliya Spotlight", "Kaliya Time Machine", "Ma jiro artifact gaar ah"],
        answer: 0,
        explain: "Kuwaan waa artifacts-ka forensics-ka Linux ugu muhiimsan.",
      },
      {
        id: "e42",
        q: "Fileless malware sababtoo ah muhiim u yahay in memory la qabto ka hor damiyaa?",
        options: ["Malware-ku wuxuu ku noolaadaa memory-ga oo keliya, wuxuu lumayaa marka la damiyo", "Malware-ku disk-ka ayuu ku jiraa", "Ma jiro isticmaal", "Waa kaliya theoretical"],
        answer: 0,
        explain: "Evidence-kan waa mid aan la heli karin haddii memory aan la qabanin ka hor damidda.",
      },
      {
        id: "e43",
        q: "Case log-ga sababta uu muhiim u yahay waa?",
        options: ["Wuxuu taageeraa report-writing dambe iyo testimony", "Waa optional", "Ma jiro sabab", "Kaliya loo baahan yahay backup"],
        answer: 0,
        explain: "Notes joogto ah waxay hubiyaan aan la iloobin faahfaahin muhiim ah.",
      },
      {
        id: "e44",
        q: "Sababta tool footprint uu muhiim u yahay memory acquisition waa?",
        options: ["Footprint weyn wuxuu beddeli karaa memory-ga la falanqeynayo", "Ma jiro saameyn", "Footprint-gu wuxuu kordhinayaa speed", "Kaliya loo isticmaalo VMs"],
        answer: 0,
        explain: "Tool-ku laftiisu wuxuu isticmaalaa memory intii uu shaqeynayo.",
      },
      {
        id: "e45",
        q: "Secure deletion tools sida shred waxay sameeyaan?",
        options: ["Overwrite gareeyaan data-ga marar badan si aan loo soo celin karin", "Waxay backup sameeyaan", "Waxay encrypt gareeyaan oo keliya", "Wax kama beddelaan"],
        answer: 0,
        explain: "Secure deletion-ku wuxuu ka dhigayaa recovery mid aan macquul ahayn.",
      },
      {
        id: "e46",
        q: "Digital evidence repository waa in uu ahaado?",
        options: ["Encrypted, backup leh, access xaddidan", "Furan qof kasta", "Aan backup lahayn", "Ma jiraan shuruudo"],
        answer: 0,
        explain: "Security-ga repository-ga wuxuu ilaaliyaa integrity iyo confidentiality-ga evidence-ka.",
      },
      {
        id: "e47",
        q: "Investigation-kan, artifact-yada ugu qiimaha badan waa?",
        options: ["USBSTOR, LNK files, Jump Lists", "Kaliya Prefetch", "Kaliya Event Logs", "Ma jiro artifact gaar ah"],
        answer: 0,
        explain: "Kuwaan si toos ah ayay ula xiriiraan USB exfiltration scenario-ga.",
      },
      {
        id: "e48",
        q: "Live collection sababta loo doorto marmarka qaarkood waa?",
        options: ["Si loo ilaaliyo volatile evidence sida memory-ga", "Si loo yareeyo waqtiga", "Waa mid keliya la isticmaalo", "Ma jiro sabab"],
        answer: 0,
        explain: "Memory iyo state-ka joogto ah way lumaan haddii mashiinka la damiyo marka hore.",
      },
      {
        id: "e49",
        q: "Kernel space waa?",
        options: ["Qaybta OS core-ku ku jiro", "Qaybta applications-ku ku shaqeeyaan", "Kaliya loo isticmaalo drivers", "Ma jiro qaybtan"],
        answer: 0,
        explain: "Kernel space waa heerka ugu sarreeya OS-ka, ka duwan user space.",
      },
      {
        id: "e50",
        q: "Fileless malware suspected, tallaabada koowaad waa?",
        options: ["Memory acquisition", "Isla markiiba disk imaging", "Warbixinta", "Xiritaanka network"],
        answer: 0,
        explain: "Memory-gu waa halka fileless malware laga heli karo — waa in la qabtaa marka hore.",
      },
    ],
  },
  "cloud-security": {
    pathSlug: "cloud-security",
    title: "SomTrust Cloud Security Certification Exam",
    timeMinutes: 60,
    passingPercent: 70,
    questions: [
      {
        id: "e1",
        q: "NSGs Azure ah waxaa lagu dabaqi karaa?",
        options: ["Subnet-level ama NIC-level", "Kaliya subnet-level", "Kaliya NIC-level", "Kaliya VNet-level"],
        answer: 0,
        explain: "Flexibility-gan wuxuu u ogolaadaa granular control.",
      },
      {
        id: "e2",
        q: "E-commerce scenario-gan, database tier-ku waa in uu ku jiro?",
        options: ["Private subnet, aan direct internet access lahayn", "Public subnet", "Ma jiro subnet loo baahan yahay", "Kaliya on-premise"],
        answer: 0,
        explain: "Data xasaasi ah waa in la ilaaliyaa exposure internet-ka.",
      },
      {
        id: "e3",
        q: "Suppression rules waxay yareeyaan?",
        options: ["False positives noise-ka", "True positives", "Ma jiro faa'iido", "Detection capability oo dhan"],
        answer: 0,
        explain: "Context enrichment-ku wuxuu ka caawiyaa in la kala saaro true/false positives.",
      },
      {
        id: "e4",
        q: "Log normalization waxay u ogolaataa?",
        options: ["Detection rules inay shaqeeyaan providers cloud oo dhan", "Ma jiro faa'iido", "Kaliya loo isticmaalo storage", "Kordhinta volume-ka logs"],
        answer: 0,
        explain: "Format isku mid ah wuxuu fududeeyaa rule-writing generic ah.",
      },
      {
        id: "e5",
        q: "DLP tools waxay ogaadaan?",
        options: ["Xog xasaasi ah (credit cards, SSNs) oo laga yaabo inay ka baxaan organization-ka", "Kaliya malware", "Ma jiro isticmaal", "Kaliya network traffic"],
        answer: 0,
        explain: "DLP-ku wuxuu falanqeeyaa content-ka si loo ogaado xog xasaasi ah.",
      },
      {
        id: "e6",
        q: "Multi-cloud log aggregation waxay u baahan tahay?",
        options: ["Tools/platforms u ogolaada isku darka logs providers kala duwan", "Ma loo baahna isku darid", "Kaliya hal provider ayaa la isticmaalaa", "Kaliya manual copying"],
        answer: 0,
        explain: "CloudTrail iyo Azure Monitor waa systems kala duwan oo u baahan integration.",
      },
      {
        id: "e7",
        q: "Containment-ka scenario-gan waa in uu ku jiro?",
        options: ["Credential revocation isla markiiba", "Kaliya monitoring dheeraad ah", "Ma jiro tallaabo", "Kaliya email alert"],
        answer: 0,
        explain: "Credential-ka la xaday waa in la baabi'iyo isla markiiba si loo joojiyo access-ka.",
      },
      {
        id: "e8",
        q: "FinOps iyo security team-yadu waa in ay?",
        options: ["La shaqeeyaan, sababtoo ah cost anomalies waxay isku dhex jiraan security", "Si gooni ah u shaqeeyaan", "Ma jiro xiriir u dhexeeya", "Kaliya security ayaa mas'uul ka ah"],
        answer: 0,
        explain: "Collaboration-ku wuxuu kordhinayaa detection capability-ga guud.",
      },
      {
        id: "e9",
        q: "WAF wuxuu xannibaa?",
        options: ["Requests khaldan (SQLi, XSS payloads) HTTP/HTTPS traffic gudaheeda", "Dhammaan traffic", "Kaliya SSH traffic", "Ma jiro isticmaal"],
        answer: 0,
        explain: "WAF-ku wuxuu falanqeeyaa application-layer traffic-ka.",
      },
      {
        id: "e10",
        q: "AssumeRole trust policy oo ballaaran wuxuu u ogolaan karaa?",
        options: ["Attacker inuu ugu gudbo accounts kale", "Ma jiro khatar", "Kaliya legit vendors ayaa access u leh", "Wuxuu xannibaa cross-account access"],
        answer: 0,
        explain: "Trust policy aan xaddidnayn waa khatar cross-account ahaan.",
      },
      {
        id: "e11",
        q: "Encryption at rest wuxuu ilaaliyaa?",
        options: ["Data-ga kaydsan (disk, database, storage)", "Data-ga intii uu socdo network-ka oo keliya", "Ma jiro isticmaal", "Kaliya passwords"],
        answer: 0,
        explain: "At rest-ku wuxuu diiradda saaraa data-ga xaaladda kaydsan.",
      },
      {
        id: "e12",
        q: "Privileged Access Workstation (PAW) waa?",
        options: ["Workstation gaar ah oo go'doonsan browsing/email caadiga ah", "Workstation caadi ah oo dhammaan employees isticmaalaan", "Kaliya laptop personal ah", "Ma jiro macno gaar ah"],
        answer: 0,
        explain: "PAW-yadu waxay yareeyaan khatarta compromise iyada oo laga fogaanayo browsing caadiga ah.",
      },
      {
        id: "e13",
        q: "Serverless-ka, cidda mas'uul ka ah runtime patching?",
        options: ["Provider-ka", "Customer-ka", "Labadaba si isku mid ah", "Ma jiro mas'uul"],
        answer: 0,
        explain: "Serverless-ku wuxuu ka saaraa customer mas'uuliyadda runtime/OS.",
      },
      {
        id: "e14",
        q: "Behavioral question (khilaaf developer team) waxay tijaabisaa?",
        options: ["Balance-ka security iyo velocity, diplomacy", "Kaliya technical skills", "Ma jiro ujeeddo", "Kaliya coding ability"],
        answer: 0,
        explain: "Soft skills-ku waa muhiim xitaa technical roles ahaan.",
      },
      {
        id: "e15",
        q: "CIDR planning muhiim u tahay sababtoo ah?",
        options: ["Si loo iska ilaaliyo IP overlap marka VPCs la isku xiro", "Ma jiro sabab", "Kaliya loo isticmaalo compliance", "Kordhinta speed-ka"],
        answer: 0,
        explain: "Overlap-ku wuxuu adkeeyaa peering ama hybrid connectivity.",
      },
      {
        id: "e16",
        q: "Containers ka duwan yihiin VMs sababtoo ah?",
        options: ["Waxay wadaagaan host OS kernel-ka, ma laha OS gooni ah", "Isku mid VMs", "Ma jiro farqi", "Containers waa VMs kale oo nooc ah"],
        answer: 0,
        explain: "Container isolation-ku waa mid ka daciifsan VM isolation (hypervisor-based).",
      },
      {
        id: "e17",
        q: "Least privilege RBAC wuxuu yareeyaa?",
        options: ["Lateral movement cluster-ka gudihiisa", "Speed-ka cluster-ka", "Ma jiro faa'iido", "Kordhinta cost oo keliya"],
        answer: 0,
        explain: "Access xaddidan wuxuu xaddidaa waxa attacker uu sameyn karo access la helay.",
      },
      {
        id: "e18",
        q: "GDPR wuxuu saameeyaa?",
        options: ["Organization kasta oo xogta EU residents maareysa, xitaa haddii uusan Europe ku jirin", "Kaliya organizations Europe ku jira", "Kaliya government agencies", "Ma jiro saameyn dibadda ah"],
        answer: 0,
        explain: "GDPR-gu wuxuu leeyahay extraterritorial scope.",
      },
      {
        id: "e19",
        q: "Log-based forensics waxaa loo isticmaalaa marka?",
        options: ["Disk/memory aan la heli karin (tusaale serverless)", "Marwalba, ma aha kaliya xaaladaha gaarka ah", "Ma jiro isticmaal", "Kaliya loo isticmaalo VMs"],
        answer: 0,
        explain: "Serverless functions ma laha disk/memory la image-gareyn karo directly.",
      },
      {
        id: "e20",
        q: "Third-party vendors scenario-gan waxay u baahan yihiin?",
        options: ["Vendor risk assessment iyo least privilege access", "Ma loo baahna assessment", "Kaliya price comparison", "Access buuxa oo aan xaddidnayn"],
        answer: 0,
        explain: "Vendor risk-ku wuxuu saameeyaa compliance posture-ka guud.",
      },
      {
        id: "e21",
        q: "Marka credential theft la shakiyo, tallaabada degdegga ah waa?",
        options: ["Rotate/baabi'i credential-ka isla markiiba", "Sug ilaa maalinta xigta", "Iska dhaaf", "Kaliya beddel password-ka user-ka"],
        answer: 0,
        explain: "Waqti degdeg ah ayaa yareeynaya window-ka access-ka attacker-ku haysto.",
      },
      {
        id: "e22",
        q: "Alert fatigue wuxuu keenaa?",
        options: ["Analyst-yadu inay iska indho tiraan alerts muhiimka ah", "Kordhinta detection accuracy", "Ma jiro saameyn", "Yareynta alerts oo dhan"],
        answer: 0,
        explain: "Noise badan wuxuu qariyaa signal-ka muhiimka ah.",
      },
      {
        id: "e23",
        q: "Marka shirkad u guurayso cloud, tallaabada ugu horreysa waa?",
        options: ["Fahamka shared responsibility model-ka service model-ka la doortay", "Isla markiiba migration-ka", "Warbixinta ugu dambaysa", "Ka baxsan planning-ka"],
        answer: 0,
        explain: "Fahamka mas'uuliyadaha waa saldhig u ah planning-ka oo dhan.",
      },
      {
        id: "e24",
        q: "Mabaadi'da guud (IAM, monitoring, IR) waxay?",
        options: ["Isku mid yihiin providers oo dhan, xitaa haddii terminology-du kala duwan tahay", "Waligeed kala duwan yihiin", "Ma jiro overlap", "Kaliya khuseeya hal provider"],
        answer: 0,
        explain: "Koorsadan wuxuu ku dhisay mabaadi' provider-agnostic ah.",
      },
      {
        id: "e25",
        q: "Data events waxay diiwaan geliyaan?",
        options: ["Resource-level operations (tusaale S3 GetObject)", "Kaliya control plane actions", "Ma jiro faa'iido", "Kaliya IAM changes"],
        answer: 0,
        explain: "Data events-ku waa granular, waxaana optional ah sababtoo ah volume-koodu weyn yahay.",
      },
      {
        id: "e26",
        q: "TDE waa?",
        options: ["Transparent Data Encryption — encryption at rest default ah", "Nooc network security ah", "Backup tool", "Ma jiro macno"],
        answer: 0,
        explain: "TDE-gu wuxuu encrypt gareeyaa database files automatically.",
      },
      {
        id: "e27",
        q: "Identity federation wuxuu u oggolaadaa?",
        options: ["Isticmaalka identity provider hal ah oo access u siiya systems badan", "Isticmaalka password kala duwan system kasta", "Ma jiro faa'iido", "Kaliya loo isticmaalo hal app"],
        answer: 0,
        explain: "Federation-ku wuxuu yareeyaa baahida credentials kala duwan.",
      },
      {
        id: "e28",
        q: "Cloud isolation-ku (security group modification) wuxuu ka dhici karaa?",
        options: ["Daqiiqado, API call ahaan", "Saacado, physical unplug ahaan", "Maalmo", "Ma jiro waqti la qiyaasi karo"],
        answer: 0,
        explain: "Cloud API-du wuxuu u ogolaadaa isolation degdeg ah marka la barbardhigo physical actions.",
      },
      {
        id: "e29",
        q: "Sababta shared responsibility model-ka loo fahmo si sax ah waa?",
        options: ["Si aan la iska filin in vendor-ku maamulo wax uusan maamulin (misconfig risk)", "Ma jiro sabab", "Kaliya loo baahan yahay compliance", "Wuxuu ka saarayaa baahida encryption"],
        answer: 0,
        explain: "Fahamka khaldan wuxuu keeni karaa security gaps aan la ogeyn.",
      },
      {
        id: "e30",
        q: "Certifications 'in progress' waa in?",
        options: ["Lagu daro LinkedIn/resume xitaa haddii aan la dhammaystirin", "La iska daayo ilaa la dhammaystiro", "Ma jiro faa'iido lagu daro", "Kaliya loo isticmaalo interviews"],
        answer: 0,
        explain: "Wuxuu muujiyaa xamaasad iyo progress joogto ah.",
      },
      {
        id: "e31",
        q: "Sababta capstone-kani muhiim u yahay portfolio-gaaga waa?",
        options: ["Wuxuu muujiyaa awoodaada dhammaystirka cloud security assessment oo dhan", "Wuxuu kaliya muujiyaa aqoon academic ah", "Ma jiro faa'iido", "Wuxuu kaliya muujiyaa typing speed"],
        answer: 0,
        explain: "Employers-yadu waxay rabaan inay arkaan awoodda dhammaystirka assessment oo dhan.",
      },
      {
        id: "e32",
        q: "Living off the land cloud style-ku wuxuu isticmaalaa?",
        options: ["Native tools/APIs legit ah si loo fuliyo code khaldan", "Kaliya malware traditional ah", "Ma jiro technique", "Kaliya physical access"],
        answer: 0,
        explain: "Cloud-native tools waxay ka dhigaan detection mid adag.",
      },
      {
        id: "e33",
        q: "KMS ujeeddadeedu waa?",
        options: ["Abuuritaanka, maamulka iyo xakamaynta encryption keys", "Kaliya storage data", "Ma jiro ujeeddo", "Kaliya network monitoring"],
        answer: 0,
        explain: "KMS waa service central ah oo encryption keys lagu maareeyo.",
      },
      {
        id: "e34",
        q: "CSPM tools waxay sameeyaan?",
        options: ["Falanqaynta joogtada ah ee configuration, barbardhigga best practices", "Kaliya hal mar sanadkii", "Ma jiro faa'iido", "Kaliya backup"],
        answer: 0,
        explain: "Continuous monitoring-ku wuxuu ogaadaa misconfigurations dhaqso ahaan.",
      },
      {
        id: "e35",
        q: "Diyaarinta hands-on questions waxay u baahan tahay?",
        options: ["Practice fikirka joogtada ah, ma aha kaliya memorization", "Kaliya cram-ka xogta", "Ma loo baahna diyaarin", "Kaliya theory akhriska"],
        answer: 0,
        explain: "Live problem-solving-ku wuxuu u baahan yahay practice hands-on ah.",
      },
      {
        id: "e36",
        q: "IAM groups waxay u oggolaadaan?",
        options: ["Isku darka users leh baahiyo permissions isku mid ah", "Kaliya hal user", "Kaliya services", "Ma jiro isticmaal"],
        answer: 0,
        explain: "Groups-ku waxay fududeeyaan maamulka permissions users badan.",
      },
      {
        id: "e37",
        q: "IaC (Terraform, CloudFormation) faa'iidadeeda ugu weyn waa?",
        options: ["Yareynta human error iyo kordhinta consistency", "Kordhinta kharashka", "Ma jiro faa'iido security ah", "Kaliya loo isticmaalo backup"],
        answer: 0,
        explain: "Code-based infrastructure wuxuu u oggolaadaa review iyo automated scanning.",
      },
      {
        id: "e38",
        q: "Authentication waa?",
        options: ["Xaqiijinta cidda ay tahay user-ku", "Go'aaminta waxa la oggol yahay", "Isku mid authorization", "Ma jiro macno"],
        answer: 0,
        explain: "Authentication-ku wuxuu ka horreeyaa authorization-ka.",
      },
      {
        id: "e39",
        q: "Alert tuning strategy-gu wuxuu ka hortagaa?",
        options: ["Alert fatigue oo keenaya in signal muhiimka ah la seego", "Ma jiro faa'iido", "Kordhinta alerts", "Kaliya loo isticmaalo cost"],
        answer: 0,
        explain: "Tuning-ku wuxuu xaqiijiyaa in analyst-yadu diiradda saaraan waxa muhiimka ah.",
      },
      {
        id: "e40",
        q: "IAM policy changes lama filaan ah waxay ku xigaan geo-anomaly-ga waxay muujinayaan?",
        options: ["Privilege escalation kadib initial access", "Ma jiro xiriir", "Backup automatic ah", "Update software"],
        answer: 0,
        explain: "Chain-ku wuxuu raacayaa pattern caadiga ah: access → escalation → abuse.",
      },
      {
        id: "e41",
        q: "Policy as code wuxuu u ogolaadaa?",
        options: ["Automation-ka enforcement/testing compliance rules", "Ma jiro faa'iido", "Kaliya documentation", "Kordhinta cost oo keliya"],
        answer: 0,
        explain: "Code-based policies waa la automate gareyn karaa, ma aha documents la akhriyo oo keliya.",
      },
      {
        id: "e42",
        q: "Leaked credentials GitHub commits ah waa tusaale?",
        options: ["Initial access vector caan ah", "Privilege escalation technique", "Data exfiltration method", "Ma jiro macno gaar ah"],
        answer: 0,
        explain: "Developers-yadu badanaa si khaldan u ku daraan credentials source code gudaheeda.",
      },
      {
        id: "e43",
        q: "Golden images faa'iidadooda waa?",
        options: ["Consistency iyo hardening instances cusub oo dhan", "Ma jiro faa'iido", "Kaliya loo isticmaalo backup", "Kordhinta cost oo keliya"],
        answer: 0,
        explain: "Templates pre-hardened ah waxay xaqiijiyaan security baseline joogto ah.",
      },
      {
        id: "e44",
        q: "MFA fatigue attack-ku wuxuu isticmaalaa?",
        options: ["Push notifications badan ilaa user-ku approve gareeyo", "Kaliya brute force password", "Kaliya SQL injection", "Ma jiro technique"],
        answer: 0,
        explain: "Cadaadis joogto ah wuxuu dhalin karaa in user-ku uu gujiyo approve iyada oo uusan doonayn.",
      },
      {
        id: "e45",
        q: "NIST IR lifecycle-ka afarta marxaladood waa?",
        options: ["Preparation, Detection/Analysis, Containment/Eradication/Recovery, Post-Incident", "Kaliya Detection iyo Response", "Kaliya Preparation", "Ma jiro marxalado la qeexay"],
        answer: 0,
        explain: "Kani waa framework standard-ka ah oo IR-ku raaco, cloud iyo on-premise labadaba.",
      },
      {
        id: "e46",
        q: "Mandatory tagging policies waxay sameeyaan?",
        options: ["Xannibaan abuurista resources aan lahayn tags waajibka ah", "Ma jiro enforcement", "Kaliya suggest gareeyaan", "Kaliya loo isticmaalo reporting"],
        answer: 0,
        explain: "Enforcement-ku wuxuu xaqiijiyaa tagging consistency-ga.",
      },
      {
        id: "e47",
        q: "Public S3 bucket (Principal '*') waa?",
        options: ["Misconfiguration halis ah oo qof kasta u oggolaanaya access", "Best practice", "Waajib dhammaan buckets", "Ma jiro khatar"],
        answer: 0,
        explain: "Wildcard principal wuxuu u oggolaadaa qof kasta internet-ka access.",
      },
      {
        id: "e48",
        q: "Public S3 buckets waa?",
        options: ["Mid ka mid ah misconfigurations-ka ugu caansan ee cloud breaches", "Best practice", "Waajib bucket kasta", "Ma jiro khatar"],
        answer: 0,
        explain: "Breaches waaweyn badanaa waxay ku bilaabmaan bucket exposure.",
      },
      {
        id: "e49",
        q: "IAM loo yiraahdo 'perimeter cusub' cloud-ka gudihiisa sababtoo ah?",
        options: ["Ma jiro perimeter network jireed sida on-premise, identity-gu waa control-ka aasaasiga ah", "IAM ma khuseeyo cloud-ka", "Firewalls-ku waa control-ka aasaasiga ah weli", "Ma jiro sabab"],
        answer: 0,
        explain: "Cloud-ka gudihiisa, access-ku wuxuu ku salaysan yahay identity, ma aha network location.",
      },
      {
        id: "e50",
        q: "PaaS-ka faa'iidadiisu waa?",
        options: ["Aan loo baahnayn in la maamulo infrastructure hoose", "Control ugu badan ee infrastructure", "Ma jiro faa'iido", "Kaliya loo isticmaalo databases"],
        answer: 0,
        explain: "PaaS-ku wuxuu u ogolaadaa developers-ka inay diiradda saaraan code-ka oo keliya.",
      },
    ],
  },
};

export function findExamBank(pathSlug: string): ExamBank | undefined {
  return EXAM_BANKS[pathSlug];
}
